<?php
/**
 * Ecommistry
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 */
 
 /**
 * @category    design
 * @package     base_default
 * @license     GNU General Public License v3.0
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getProducts();
    $_helper = $this->helper('catalog/output');
    $ecommistryHelper = Mage::helper('productlist');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products to display.') ?></p>
<?php else: ?>
<div class="category-products <?php if($this->getMode() == 'slider'): ?>flexslider carousel<?php endif;?>">
	<div class="toolbar">
		<div class="sorter">
			<p class="view-mode">
				<?php $_modes = $this->getModes(); ?>
				<?php if($_modes && count($_modes)>1): ?>
				<label><?php echo $this->__('View as') ?>:</label>
				<?php foreach ($this->getModes() as $mode): ?>
					<?php if($this->getMode() == $mode['value']): ?>
						<strong title="<?php echo $mode['label'] ?>" class="<?php echo strtolower($mode['value']); ?>"><?php echo $mode['label'] ?></strong>&nbsp;
					<?php else: ?>
						<a href="<?php echo $ecommistryHelper->getProductListUri()."?mode=".strtolower($mode['value']);?>" title="<?php echo $mode['label'] ?>" class="<?php echo strtolower($mode['value']); ?>"><?php echo $mode['label'] ?></a>&nbsp;
					<?php endif; ?>
				<?php endforeach; ?>
				<?php endif; ?>
			</p>
		</div>
	</div>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col <?php if($this->getMode() == 'slider'): ?>slides<?php endif;?>">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <div class="actions">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
    
	<?php // Slider mode ?>
    <?php if($this->getMode() == 'slider'): ?>
		<script>
			jQuery(window).load(function() {
			  jQuery('.flexslider').flexslider({
				animation: "slide",
				animationLoop: true,
				itemWidth: 220,
				itemMargin: 22,
				move: 1,
				controlNav: true,
				slideshowSpeed: 2500,
				minItems: 2,
				maxItems: <?php echo $_columnCount ?>
			  });
			});
		</script>
		<style>
			.products-grid--max-5-col > li:nth-child(5n+1),.products-grid--max-3-col > li:nth-child(3n+1), .products-grid > li:nth-child(odd){ clear:none !important; }
			
		</style>
    <?php endif; ?>
</div>
<?php endif; ?>